---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: JUSDETE
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: JUSBETE
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: JUSDQTE
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: JUSBQTE
  checked: true
name: Determinación y análisis de procedimiento
