---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: JUSDETE
  checked: false
- value: JUSBETE
  checked: false
- value: JUSDQTE
  checked: false
- value: JUSBQTE
  checked: true
name: Determinación y análisis de procedimiento
