---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: '15'
  checked: false
- value: '34'
  checked: false
- value: '14'
  checked: true
- value: '8'
  checked: false
name: Razonamiento lógico
