---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '15'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '34'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '14'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '8'
  checked: false
name: Razonamiento lógico
