---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No importaba la posición desde donde se mirara el telégrafo óptico, siempre
    presentaba información.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Debido a que la señal producida por el telégrafo óptico era plana, resultaba
    muy complicado trazar curvas en las líneas de comunicación.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El buen funcionamiento del telégrafo óptico dependía de las condiciones climáticas.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La solución para usar el telégrafo óptico de noche fue fijar faroles.
  checked: false
name: Comprensión de texto
